spring.application.name=productmanagment

server.port=5000

spring.datasource.url=jdbc:mysql://localhost:3306/productmanagment?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.open-in-view=true